-- ============================================================================
-- PrepMaster - Feedbacks table
-- Migration: 20260926190000_create_feedbacks.sql
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1. Verify the existing Students table contract before creating the FK.
--    This deliberately fails with a clear message instead of creating a
--    partially-correct schema if the prerequisite is missing/mismatched.
-- ---------------------------------------------------------------------------

do $$
begin
    if to_regclass('public.students') is null then
        raise exception
            'public.students does not exist. Create the existing Students '
            'profile table before applying the Feedbacks migration.';
    end if;

    if not exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'students'
          and column_name = 'student_id'
          and data_type = 'bigint'
    ) then
        raise exception
            'public.students.student_id must exist and be BIGINT before '
            'creating public.feedbacks.';
    end if;
end $$;


-- ---------------------------------------------------------------------------
-- 2. Create Feedbacks
--
-- ER mapping:
--   FeedbackId  -> feedback_id
--   Description -> description
--   Type        -> type
--   isSpam      -> is_spam
--   isBookmark  -> is_bookmark
--   isSeen      -> is_seen
--   StudentId   -> student_id
--
-- PostgreSQL BIGINT = signed 64-bit integer.
-- IDENTITY generates the value automatically.
-- ---------------------------------------------------------------------------

create table public.feedbacks (
    feedback_id bigint generated by default as identity primary key,

    description varchar(1000) not null,

    type varchar(30) not null,

    is_spam boolean not null default false,

    is_bookmark boolean not null default false,

    is_seen boolean not null default false,

    student_id bigint not null
        references public.students(student_id)
);


-- ---------------------------------------------------------------------------
-- 3. Index the student relationship.
--    This supports fetching a student's feedback efficiently later.
-- ---------------------------------------------------------------------------

create index feedbacks_student_id_idx
    on public.feedbacks(student_id);


-- ---------------------------------------------------------------------------
-- 4. Enforce the one-way moderation rule at database level.
--
--    Allowed:
--      false -> false
--      false -> true
--      true  -> true
--
--    Forbidden:
--      true -> false
--
--    This protects the rule even if somebody bypasses the React UI.
-- ---------------------------------------------------------------------------

create or replace function public.prevent_feedback_status_reversal()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
    if old.is_spam = true and new.is_spam = false then
        raise exception
            'feedbacks.is_spam cannot be changed from true to false';
    end if;

    if old.is_bookmark = true and new.is_bookmark = false then
        raise exception
            'feedbacks.is_bookmark cannot be changed from true to false';
    end if;

    if old.is_seen = true and new.is_seen = false then
        raise exception
            'feedbacks.is_seen cannot be changed from true to false';
    end if;

    return new;
end;
$$;


drop trigger if exists feedbacks_prevent_status_reversal
    on public.feedbacks;

create trigger feedbacks_prevent_status_reversal
before update on public.feedbacks
for each row
execute function public.prevent_feedback_status_reversal();


-- ---------------------------------------------------------------------------
-- 5. Enable Row Level Security.
--
--    For now the application will access Feedbacks through the backend/server
--    path. Direct client access is therefore blocked.
-- ---------------------------------------------------------------------------

alter table public.feedbacks enable row level security;
alter table public.feedbacks force row level security;


-- ---------------------------------------------------------------------------
-- 6. Keep direct browser access closed.
--
--    The backend will use the privileged Supabase server-side role later.
--    Students/admins must not receive unrestricted direct table privileges.
-- ---------------------------------------------------------------------------

revoke all on table public.feedbacks from anon, authenticated;


-- ---------------------------------------------------------------------------
-- 7. Allow the server-side Supabase service role to perform the database work.
-- ---------------------------------------------------------------------------

grant select, insert, update
    on table public.feedbacks
    to service_role;


commit;

notify pgrst, 'reload schema';